---
- name: Install nmtrust
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: nmtrust-git
  tags:
    - aur

- name: Create nmtrust config directory
  file:
    path: /etc/nmtrust
    state: directory

- name: Push trusted network list
  template:
    src: trusted_networks.j2
    dest: /etc/nmtrust/trusted_networks

- name: Verify trusted unit list exists
  file:
    path: /etc/nmtrust/trusted_units
    state: touch
