user:
  name: alulord
  uid: 1000
  group: users
  shell: /usr/bin/zsh
  log:
    dir: .log
    rotate: 8
  timezone: Europe/Bratislava

bootloader:
  path: /boot
  theme_path: refind-theme-regular
  theme_repo: https://github.com/bobafetthotmail/refind-theme-regular.git
  kernel_parameters:
  silent: True

additional_hosts: |
  192.168.2.102 sonarr.rasp plex.rasp radarr.rasp jackett.rasp ombi.rasp resilio.rasp traefik.rasp monit.rasp muximux.rasp
  127.0.0.1 sonarr.docker plex.docker radarr.docker jackett.docker ombi.docker resilio.docker traefik.docker monit.docker muximux.docker
  127.0.0.1 admin.odin auth.odin platform.odin helpdesk.odin frm.odin web.odin rest.odin rabbitmq.odin phpmyadmin.odin services.odin
  10.1.13.70 kibana.ws.int

dotfiles:
  url: git@github.com:peter-si/arch-dotfiles.git
  name: .dotfiles.git

pacman:
  base_packages:
    - base-devel
    - man-db
    - man-pages
    - pacman-contrib
    - fwupd
    - dmidecode
    - tmux
    - git
    - rsync
    - coreutils
    - moreutils
    - dateutils
    - bc
    - arch-wiki-lite
    - arch-wiki-docs
    - python-keyring
    - python-secretstorage
    - pv
    - jq
    - screen
    - nano
    - wget
    - zsh
    - alacritty
    - jre-openjdk
  packages:
    - gsimplecal
    - neofetch
    - rsync
    - pacman-contrib
    - papirus-icon-theme
    - lm_sensors
    - archiso
    - gnome-calculator
    - jre-openjdk
    - gucharmap
  fonts:
    - adobe-source-code-pro-fonts
    - cantarell-fonts
    - gsfonts
    - noto-fonts
    - noto-fonts-emoji
    - terminus-font
    - tex-gyre-fonts
    - ttf-caladea
    - ttf-carlito
    - ttf-dejavu
    - ttf-droid
    - ttf-fira-mono
    - ttf-ibm-plex
    - ttf-inconsolata
    - ttf-liberation
    - ttf-opensans
    - ttf-ubuntu-font-family
    - ttf-font-awesome

aur:
  packages:
    - yay
    - ctop
    - downgrade
    - myrepos
    - teamviewer
    - yay
    - nvme-cli
  fonts:
    - ttf-bitstream-charter
    - ttf-cooper-hewitt
    - ttf-courier-prime
    - ttf-heuristica
    - ttf-merriweather
    - ttf-merriweather-sans
    - ttf-oswald
    - ttf-quintessential
    - ttf-signika
    - nerd-fonts-fira-code
    - nerd-fonts-jetbrains-mono
    - ttf-font-awesome-4
    - ttf-weather-icons

ssh:
  port: 22
  user_dir: /install/.ssh
  enable_sshd: False

gnupg:
  enable_agent: True
  emulate_ssh: True

network:
  spoof_mac: True
  conn_check:
    interval: 0
  trusted_uuid:
    - bfa4a571-e6b0-46f1-84ca-e8bce047dd64
    - 7fd5436b-ce00-4659-91ab-406b9fa1a1e8
    - 535ee41f-f3f9-30bd-92d8-8a9e227621de

wireless_packages:
  - wireless_tools
  - iw
  - iwd

video_drivers:

browser_choices:
  - firefox -P default
  - firefox -P work
  - firewarden chromium
  - tor-browser-en

passwordless_sudo:
  - /usr/bin/openvpn*

fingerprint: False

#unbound:
#  tls: True
#  roothints_update: trusted
#  nameservers:
#    - 1.1.1.1@853#cloudflare-dns.com  # Cloudflare
#    - 9.9.9.9@853#dns.quad9.net  # Quad9
#  private_domains:
#    - odin
#    - rasp
#    - docker
#  allow_lan_dns: True

bluetooth:
  disable: False

firejail:
  blacklist:
    - ~/.calendars
    - ~/.config/vdirsyncer
    - ~/.contacts
    - ~/.keys
    - ~/.mbsyncrc
    - ~/.offlineimap
    - ~/.offlineimaprc
    - ~/.password-store
    - ~/.vdirsyncer
    - ~/library
    - ~/.cache/keepassxc
    - ~/.cache/protonmail
    - ~/.config/Bitwarden
    - /.config/Bitwarden/Bitwarden\ CLI
    - /.config/syncthing
    - /.config/syncthing-gtk
    - /.local/tasks

journal:
  max_size: 500M

udisks:
  auto_mount: False
  shared_mount: True

hostsctl:
  url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

x:
  middle_click_button: "274"
  keyboard_model: "pc105"

display_manager:

desktop_environment: i3

gdm:
  sound: False
  font_scaling_factor: 1
  logo_path: False
  touchpad:
    tap_to_click: True
  accessibility_menu: True

gnome:
  night_light:
    enabled: True
    color_temperature: 4000 # in Kelvin
  date_time:
    show_date_in_clock: True
    show_weeks_in_calendar: True
  battery:
    show_percentage: True
  power:
    sleep_timeout_when_computer_on_ac: 3600 # in seconds
    timeout_action_when_computer_on_ac: suspend
    sleep_timeout_when_computer_on_battery: 1800 # in seconds
    timeout_action_when_computer_on_battery: suspend
    power_button_action: suspend
  touchpad:
    tap_to_click: True
    natural_scrolling: True
    disabled_while_typing: True
  online_accounts_support: True
  lock_screen:
    automatic_lock: True
    lock_screen_after_blank_for: 0 # in seconds
    show_notifications: True
    show_full_name_of_user: True
  theme:
    theme_name: Adwaita
    icon_theme_name: Adwaita
    font_name: Dejavu Sans 13
    dark_variant: True
  gnome_shell:
    disable_top_left_hot_corner: False
    extensions_support: True

hardened:
  enable_namespaces: true

syncthing:
  run_on: trusted
  open_ports: False

mirrorlist:
  run_on: trusted

pkgfile:
  run_on: trusted

tor:
  run_on: trusted

localtime:
  run_on: trusted
