---
- name: Install chrony
  pacman: name=chrony state=present

- name: Install chrony networkmanager dispatcher
  become: yes
  become_user: "{{ user.name }}"
  aur: name=networkmanager-dispatcher-chrony
  tags:
    - aur
    - networkmanager

- name: Push chrony configuration file
  copy: src=chrony.conf dest=/etc/chrony.conf
  notify:
    - restart chrony

- name: Enable and start chrony
  service: name=chronyd.service enabled=yes state=started
