---
- name: Set timesyncd pools
  lineinfile:
    regexp: "^\\#?NTP="
    line: NTP=europe.pool.ntp.org 0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org
    path: /etc/systemd/timesyncd.conf

- name: Enable timesyncd
  systemd:
    name: systemd-timesyncd.service
    enabled: yes
  notify:
    - Start timesyncd
    - Enable ntp
