---
- name: Install RedShift and dependencies
  pacman:
    name:
      - librsvg
      - python-gobject
      - python-xdg
      - redshift
    state: present

- name: Jail RedShift
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/redshift
        state=link
  tags:
    - firejail

- name: Jail RedShift GTK
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/redshift-gtk
        state=link
  tags:
    - firejail

- name: Push RedShift firejail profile
  copy: src=firejail/redshift.profile dest=/usr/local/etc/firejail/redshift.profile
  notify:
    - activate firejail profiles
  tags:
    - firejail

- name: Push RedShift GTK firejail profile
  copy: src=firejail/redshift.profile dest=/usr/local/etc/firejail/redshift-gtk.profile
  notify:
    - activate firejail profiles
  tags:
    - firejail

- name: Push Geoclue user service
  copy: src=geoclue-agent.service dest=/home/{{ user.name }}/.config/systemd/user/geoclue-agent.service

- name: Create user systemd default.target.wants dir
  file:
    path: "/home/{{ user.name }}/.config/systemd/user/default.target.wants"
    state: directory
    recurse: yes
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: 0755

- name: Enable Geoclue user service
  file:
    dest: "/home/{{ user.name }}/.config/systemd/user/default.target.wants/geoclue-agent.service"
    src: "/home/{{ user.name }}/.config/systemd/user/geoclue-agent.service"
    state: link
  notify: start Geoclue user service

- name: Allow RedShift to access geoclue
  blockinfile:
    dest: /etc/geoclue/geoclue.conf
    block: |
      [redshift]
      allowed=true
      system=false
      users=
