---
- name: Install mpv
  pacman: name=mpv state=present

- name: Jail mpv
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/mpv
        state=link
  tags:
    - firejail
  when: firejail.enabled is defined and firejail.enabled == True

- name: Push play script
  copy: src=play.sh dest=/usr/local/bin/play mode=0755
