---
- hosts:
    - cli
    - gui
  become: yes
  roles:
    - { role: base, tags: [ 'base' ] }
    - { role: mkinitcpio, tags: [ 'mkinitcpio' ] }
    - { role: bootloader, tags: [ 'bootloader' ] }
    - { role: gnupg, tags: [ 'gnupg' ] }
    - { role: sysmon, tags: [ 'sysmon' ] }
    - { role: cron, tags: [ 'cron' ] }
    - { role: hardened, tags: [ 'hardened' ], when: "hardened is defined" }
    - { role: ssh, tags: [ 'ssh' ] }
    - { role: editors, tags: [ 'editors' ] }
    - { role: fonts, tags: [ 'fonts' ] }
    - { role: ntp, tags: [ 'ntp' ] }
    - { role: iptables, tags: [ 'iptables' ] }
    - { role: video_drivers, tags: [ 'video_drivers' ] }
    - { role: nettools, tags: [ 'nettools' ] }
    - { role: openresolv, tags: [ 'openresolv' ] }
    - { role: networkmanager, tags: [ 'networkmanager' ] }
    - { role: gnome-keyring, tags: [ 'gnome-keyring' ] }
    - { role: nmtrust, tags: [ 'nmtrust' ] }
    - { role: filesystems, tags: [ 'filesystems' ] }
    - { role: archive, tags: [ 'archive' ] }
    - { role: taskwarrior, tags: [ 'taskwarrior' ] }
    - { role: virtualenv, tags: [ 'virtualenv' ] }
    - { role: wormhole, tags: [ 'wormhole' ] }
    - { role: hostsctl, tags: [ 'hostsctl' ], when: "hostsctl is defined" }
    - { role: mirrorlist, tags: [ 'mirrorlist' ], when: "mirrorlist is defined" }
    - { role: pkgfile, tags: [ 'pkgfile' ], when: "pkgfile is defined" }
    - { role: pydev, tags: [ 'pydev' ] }
    - { role: docker, tags: [ 'docker' ] }
    - { role: dotfiles, tags: ['dotfiles'] }
    - { role: ssd, tags: [ 'ssd' ] }

- hosts: gui
  become: yes
  roles:
    - { role: x, tags: ['x'] }
    - { role: no-dm, tags: [ 'no-dm' ], when: "display_manager == 'no-dm'" }
    - { role: lightdm, tags: ['lightdm'], when: "display_manager == 'lightdm'" }
    - { role: gdm, tags: ['gdm'], when: "display_manager == 'gdm'" }
    - { role: i3, tags: ['i3'], when: "desktop_environment == 'i3'" }
    - { role: xfce-i3, tags: ['xfce-i3'], when: "desktop_environment == 'xfce-i3'" }
    - { role: gnome, tags: ['gnome'], when: "desktop_environment == 'gnome'" }
    - { role: wireless, tags: ['wireless'] }
    - { role: macchiato, tags: [ 'macchiato' ] }
    - { role: firejail, tags: [ 'firejail' ], when: firejail.enabled is defined and firejail.enabled == True }
#    - { role: unbound, tags: ['unbound'] }
    - { role: tor, tags: ['tor'], when: "tor is defined" }
    - { role: udisks, tags: ['udisks'] }
    - { role: spell, tags: ['spell'] }
    - { role: yubikey, tags: ['yubikey'] }
    - { role: media, tags: ['media'] }
    - { role: mpv, tags: ['mpv'] }
    - { role: mail, tags: ['mail'] }
    - { role: cups, tags: ['cups'] }
    - { role: office, tags: ['office'] }
    - { role: pdf, tags: ['pdf'] }
    - { role: torrent, tags: ['torrent'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    - { role: sound, tags: ['sound'] }
    - { role: parcimonie, tags: ['parcimonie'], when: "tor is defined" }
    - { role: localtime, tags: ['localtime'], when: "localtime is defined" }
    - { role: clipboard, tags: ['clipboard'] }
    - { role: wttr, tags: ['wttr'] }
    - { role: vpn, tags: ['vpn'] }
    - { role: steam, tags: ['steam'] }
#    - { role: signal, tags: [ 'signal' ] }
    - { role: jetbrains, tags: ['jetbrains'] }
    - { role: spotify, tags: ['spotify'] }
    - { role: filebrowser, tags: ['filebrowser'] }
    - { role: syncthing, tags: [ 'syncthing' ], when: "syncthing is defined" }
    - { role: nextcloud, tags: [ 'nextcloud' ], when: "nextcloud is defined" }
    - { role: browsers, tags: ['browsers'] }
    - { role: filezilla, tags: ['filezilla'] }
    - { role: seahorse, tags: ['seahorse'] }

- hosts: desktop
  become: yes
  roles:
    - { role: logitech, tags: [ 'logitech' ] }

- hosts:
    - alu-kube-admin
  become: yes
  roles:
    - { role: redshift, tags: ['redshift'] }
    - { role: kubernetes, tags: [ 'kubernetes' ] }
#    - { role: udev, tags: [ 'udev' ] }

- hosts: asus
  become: yes
  roles:
    - { role: tlp, tags: ['tlp'] }
    - { role: laptop, tags: ['laptop'] }
    - { role: logitech, tags: [ 'logitech' ] }
    - { role: asus, tags: ['asus'] }
    - { role: bluetooth, tags: ['bluetooth'], when: "bluetooth is defined" }

#    - { role: thinkpad, tags: ['thinkpad'], when: "'ThinkPad' in ansible_product_version" }
#    - { role: optical, tags: ['optical'] }


