---
- name: Install Network tools
  pacman:
    name:
      - openvpn
      - ngrep
      - mtr
      - net-tools
      - bind-tools
      - whois
      - netcat
      - nmap
      - tcpdump
      - wireshark-qt
      - socat
      - nethogs
      - bmon
      - speedtest-cli
      - wireguard-tools
    state: present

- name: Add user to wireshark group
  user: name={{ user.name }} groups=wireshark append=yes
  tags:
    - user

- name: Enable and start avahi-daemon
  service:
    name: avahi-daemon.service
    enabled: yes
  notify: start avahi-daemon dispatcher
