---
- name: Install phpstorm
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name:
      - phpstorm
      - phpstorm-url-handler

- name: Install jetbrains-jre
  become: yes
  become_user: "{{ user.name }}"
  aur: name=phpstorm-jre user="{{ user.name }}"
