---
- name: restart unbound
  systemd: name=unbound state=restarted
  when: running_in_chroot == False

- name: Enable and start Unbound
  systemd:
    name: unbound.service
    state: started
  when: running_in_chroot == False

- name: restart roothints
  systemd: name=roothints.timer state=restarted
  when: unbound.roothints_update == "all" and running_in_chroot == False
