---
- name: restart paccache
  service:
    name: paccache.timer
    state: restarted
  when: ansible_is_chroot == False

- name: start paccache
  service:
    name: paccache.timer
    state: started
  when: ansible_is_chroot == False

- name: start user systemd instance
  service:
    name: "user@{{ user.uid }}"
    state: started
  when: ansible_is_chroot == False
