---
- name: restart paccache
  systemd:
    name: paccache.timer
    state: restarted
  when: running_in_chroot == False

- name: start paccache
  systemd:
    name: paccache.timer
    state: started
  when: running_in_chroot == False

- name: start user systemd instance
  systemd:
    name: "user@{{ user.uid }}"
    state: started
  when: running_in_chroot == False
