---
- name: restart paccache
  service:
    name: paccache.timer
    state: restarted

- name: start user systemd instance
  service:
    name: "user@{{ user.uid }}"
    state: started
  when: ansible_is_chroot == False
