---
- name: Push ipv4 firewall config
  template: src=iptables.rules.j2 dest=/etc/iptables/iptables.rules

- name: Enable and start iptables
  systemd: name=iptables.service enabled=yes

- name: Push ipv6 firewall config
  template: src=ip6tables.rules.j2 dest=/etc/iptables/ip6tables.rules

- name: Enable and start ip6tables
  systemd: name=ip6tables.service enabled=yes
