---
- name: Install Steam
  pacman:
    name:
      - steam
      - lib32-fontconfig
      - ttf-liberation
    state: present

- name: Jail Steam
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/steam
        state=link
  tags:
    - steam
    - firejail
  when: firejail.enabled is defined and firejail.enabled == True
