---
- name: Install hostsctl
  aur: name=hostsctl user={{ user.name }}
  tags:
    - aur

- name: Push hostsctl config
  template: src=hostsctl.conf.j2 dest=/etc/hostsctl.conf

- name: Update hostsctl
  command: hostsctl update

- name: Update hostsctl regulary
  copy:
    src: update-hostsctl.sh
    dest: /etc/cron.monthly/update-hostsctl
