---
- name: Install gnupg
  pacman:
    name: gnupg
    state: present

- name: Enable gpg-agent.socket
  systemd:
    name: gpg-agent.socket
    scope: user
    enabled: yes
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  notify: start gpg-agent
  when: gnupg.enable_agent == True

- name: Enable dirmngr.socket
  systemd:
    name: dirmngr.socket
    scope: user
    enabled: yes
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  notify: start dirmngr
  when: gnupg.enable_agent == True

- name: Enable gpg-agent-ssh.socket
  systemd:
    name: gpg-agent-ssh.socket
    scope: user
    enabled: yes
  become: yes
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  notify: start gpg-agent-ssh
  when: gnupg.enable_agent == True and gnupg.emulate_ssh == True
