---
- name: Install Okular
  pacman:
    name: epdfview
    state: present
  tags:
    - epdfview

# TODO jail epdfview
#- name: Jail Okular
#  file:
#    src: /usr/bin/firejail
#    dest: /usr/local/bin/okular
#    state: link
#  tags:
#    - okular
#    - firejail
#
#- name: Verify Okular firejail local profile exists
#  file:
#    path: /etc/firejail/okular.local
#    state: touch
#  tags:
#    - okular
#    - firejail
#
#- name: Restrict Okular network access
#  lineinfile:
#    dest: /etc/firejail/okular.local
#    regexp: "^net"
#    line: "net none"
#  tags:
#    - okular
#    - firejail

- name: Set epdfview as default PDF viewer
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "^application/pdf"
    state: present
    line: "application/pdf=epdfview.desktop"
  tags:
    - zathura
