---
- name: Install OpenSSH
  pacman: name=openssh state=present

- name: Push OpenSSH daemon configuration file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config

- name: Create OpenSSH systemd unit file directory
  file: path=/etc/systemd/system/sshd.socket.d state=directory

- name: Push OpenSSH socket unit file
  template: src=sshd-socket-override.conf.j2 dest=/etc/systemd/system/sshd.socket.d/override.conf
  notify:
    - reload systemd config
    - restart sshd

- name: Enable and start OpenSSH
  systemd: name=sshd.service enabled=yes
  when: ssh.enable_sshd is defined and ssh.enable_sshd == True
  notify: start sshd

- name: Disable and stop OpenSSH
  systemd: name=sshd.service enabled=no
  when: ssh.enable_sshd is defined and ssh.enable_sshd == False
  notify: stop sshd

- name: Copy fuse configuration file
  copy: src=fuse.conf dest=/etc/fuse.conf

- name: Install keychain
  pacman: name=keychain state=present

- name: Install x11-ask-pass
  pacman: name=x11-ssh-askpass state=present

- name: Make directory for user SSH key
  file: path=/home/{{ user.name }}/.ssh state=directory owner={{ user.name }} group={{ user.group }} mode=0700

- name: Copy user SSH keys
  copy: src={{ ssh.user_dir }}/ dest=/home/{{ user.name }}/.ssh mode=600 owner={{ user.name }} group={{ user.group }}
  when: ssh.user_dir is defined
