---
- name: Install reflector
  pacman:
    name: reflector
    state: present

- name: Push pacman mirror list update hook
  copy:
    src: mirrorlist.hook
    dest: /etc/pacman.d/hooks/mirrorlist.hook

- include_tasks: roles/nmtrust/tasks/unit.yaml
  vars:
    unit: reflector.timer
    run_on: "{{ mirrorlist.run_on }}"
