---
- name: restart chrony
  systemd: name=chronyd.service state=restarted
  when: ansible_is_chroot == False

- name: start chrony
  systemd: name=chronyd.service state=started
  when: ansible_is_chroot == False
