---
- name: Install dictd
  pacman:
    name: dictd
    state: present

- name: Install flex
  pacman:
    name: flex
    state: present

- name: Install GNU Collaborative International Dictionary of English
  aur:
    name: dict-gcide
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - aur

- name: Install WordNet database
  aur:
    name: dict-wn
    user: "{{ user.name }}"
  tags:
    - aur

- name: Install Moby thesaurus
  aur:
    name: dict-moby-thesaurus
    user: "{{ user.name }}"
  tags:
    - aur

- name: Enable and start dictd
  service:
    name: dictd.service
    enabled: yes
    state: started
