---
- name: Install Spotify
  become: yes
  become_user: "{{ user.name }}"
  aur: name=spotify skip_pgp_check=yes

- name: Jail Spotify
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/spotify
    state: link
  tags:
    - firejail
