---
- name: Install XFCE and i3 packages
  pacman:
    name:
      - dunst
      - python-pywal
      - python-dbus
      - picom
      - exo
      - garcon
      - libxfce4ui
      - libxfce4util
      - thunar
      - thunar-volman
      - thunar-media-tags-plugin
      - thunar-archive-plugin
      - tumbler
      - xfce4-dev-tools
      - xfce4-power-manager
      - xfce4-session
      - xfce4-settings
      - xfconf
    state: present

- name: Install XFCE and i3 aur packages
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name:
      - rofi-git
      - polybar
      - python-fontawesome
      - bspi-git
  tags:
    - aur

- name: Copy the autostart scripts
  copy: src=/usr/share/applications/{{item}} dest=/home/{{ user.name }}/.config/autostart/ owner={{ user.name }} group={{ user.group }}
  with_items:
    - picom.desktop
    - nm-applet.desktop
    - redshift-gtk.desktop
    - protonmail-bridge.desktop
    - spotify.desktop
    - thunderbird.desktop

- name: Add bspwm to autostart
  copy: src=bspwm.desktop dest=/home/{{ user.name }}/.config/autostart/ owner={{ user.name }} group={{ user.group }}

- name: Remove previous xfce4 sessions
  file: path=/home/{{ user.name }}/.cache/sessions state=absent

- name: Create xfce4 configuration directory in user home
  file: path=/home/{{ user.name }}/.config/xfce4/xfconf/xfce-perchannel-xml owner={{ user.name }} group={{ user.group }} state=directory

- name: Copy xfce4 configuration file
  copy: src=xfce/xfce4-session.xml dest=/home/{{ user.name }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml owner={{ user.name }} group={{ user.group }}
