---
- name: Install i3 packages
  pacman:
    name:
      - dunst
      - python-pywal
      - python-dbus
      - picom
      - i3-gaps
    state: present

- name: Install i3 aur packages
  aur:
    user: "{{ user.name }}"
    name:
      - i3-volume
      - autotiling
      - rofi-git
      - polybar
      - xidlehook
      - python-fontawesome
      - i3gopher
      - i3icons2-git
      - i3lock-color
      - betterlockscreen
  tags:
    - aur

- name: Verify that default applications file exists
  file: path=/etc/xdg/mimeapps.list state=touch

- name: Verify header in default applications file
  lineinfile: dest=/etc/xdg/mimeapps.list
              state=present
              line='[Default Applications]'
              insertbefore=BOF

- name: Create directory for betterlockscreen drop-in service
  file: path=/etc/systemd/system/betterlockscreen@{{ user.name }}.d state=directory

- name: Override betterlockscreen service
  template:
    src: "betterlockscreen@.service"
    dest: "/etc/systemd/system/betterlockscreen@{{ user.name }}.d/override-locker.conf"
  notify: reload systemd config

- name: Enable betterlockscreen sleep hook
  systemd:
    name: "betterlockscreen@{{ user.name }}.service"
    enabled: yes
  notify: start betterlockscreen
