---
- name: Install GNOME
  pacman:
    name:
      - gnome
      - gnome-extra
      - gnome-tweaks
      - xorg-server-xwayland
    state: present

- include: dconf.yaml
- include: gtk.yaml
- include: gnome_shell.yaml
- include: online_accounts.yaml
