---
- name: start filesystem TRIM timer
  systemd: name=btrfs-trim.timer state=started
  when: running_in_chroot == False

- name: start filesystem Balance timer
  systemd: name=btrfs-balance.timer state=started
  when: running_in_chroot == False
