---
- name: restart cron
  systemd: name=cronie.service state=restarted
  when: running_in_chroot == False

- name: start cron
  systemd: name=cronie.service state=started
  when: running_in_chroot == False
