---
- name: Install TLP
  pacman:
    name:
      - x86_energy_perf_policy
      - ethtool
      - tlp
      - tlp-rdw
    state: present
  tags:
    - tlp

- name: Push TLP battery threshold config
  copy:
    src: 20-battery.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp
  tags:
    - tlp

- name: Push TLP radio device config
  copy:
    src: 20-rdw.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp
  tags:
    - tlp

- name: Push TLP PCIe config
  copy:
    src: 20-pcie.conf
    dest: /etc/tlp.d/
  notify:
    - restart tlp
  tags:
    - tlp

- name: Mask systemd radio service
  command: systemctl mask systemd-rfkill.service
  tags:
    - tlp

- name: Mask systemd radio socket
  command: systemctl mask systemd-rfkill.socket
  tags:
    - tlp

- name: Enable TLP
  systemd:
    name: tlp.service
    enabled: yes
  tags:
    - tlp
