---
- name: Install YubiKey Personalization GUI
  pacman: name=yubikey-personalization-gui state=present

- name: Install smartcard libs/tools
  pacman:
    name:
      - pcsclite
      - libusb-compat
      - ccid
      - libfido2
      - pam-u2f
    state: present
