---
- name: Install filesystem packages
  pacman:
    name:
      - dosfstools
      - ntfs-3g
      - exfat-utils
      - btrfs-progs
      - snapper
      - snap-pac
    state: present

- name: Copy snapper config
  copy:
    dest: /etc/snapper/configs/root
    src: root
  tags: snapper
