---
- name: Edit mkinitcpio config
  lineinfile:
    path: /etc/mkinitcpio.conf
    line: "HOOKS=(base systemd autodetect keyboard sd-vconsole sd-encrypt modconf block filesystems btrfs)"
    regexp: "^HOOKS="
  notify:
    - rebuild bootloader
  when: bootloader.plymouth is not defined or bootloader.plymouth == False

- name: Edit mkinitcpio config
  lineinfile:
    path: /etc/mkinitcpio.conf
    line: "HOOKS=(base systemd autodetect keyboard sd-plymouth sd-vconsole sd-encrypt modconf block filesystems btrfs)"
    regexp: "^HOOKS="
  notify:
    - rebuild bootloader
  when: bootloader.plymouth is defined and bootloader.plymouth == True
