---
- name: Install Protonmail brdige
  aur: name=protonmail-bridge-bin user="{{ user.name }}"

- name: Install Mailspring
  aur: name=mailspring-libre user="{{ user.name }}"

# TODO firejail mailsync and protonmail-bridge
# possibly run only on trusted networks
