---
- name: Install parcimonie.sh
  become: yes
  become_user: "{{ user.name }}"
  aur:
    use: makepkg
    name: parcimonie-sh-git
    skip_pgp_check: yes
  tags:
    - aur

- name: Push parcimonie.sh user configuration
  template:
    src: user.conf.j2
    dest: /etc/parcimonie.sh.d/{{ user.name }}.conf

- include_tasks: roles/nmtrust/tasks/unit.yaml
  vars:
    unit: "parcimonie.sh@{{ user.name }}.service"
    run_on: "{{ tor.run_on }}"
