---
- name: Install parcimonie.sh
  aur:
    name: parcimonie-sh-git
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - aur

- name: Push parcimonie.sh user configuration
  template:
    src: user.conf.j2
    dest: /etc/parcimonie.sh.d/{{ user.name }}.conf

- include_tasks: roles/nmtrust/tasks/unit.yaml
  vars:
      unit: "parcimonie.sh@{{ user.name }}.service"
      run_on: "{{ tor.run_on }}"
