---
- name: Install firejail
  pacman:
    name: firejail
    state: present
  when: firejail.enabled is defined and firejail.enabled == True

- name: Install firewarden
  become: yes
  become_user: "{{ user.name }}"
  aur: name=firewarden
  tags:
    - aur

- name: Install firejail profile update script
  copy:
    src: profile-activate.sh
    dest: /usr/local/bin/profile-activate
    mode: 0755

- name: Create firejail profile directory
  file:
    path: /usr/local/etc/firejail
    state: directory

- name: Add blacklist to globals
  lineinfile:
    dest: /etc/firejail/globals.local
    state: present
    line: "blacklist {{ item }}"
    create: yes
  with_items: "{{ firejail.blacklist }}"
