---
- name: Install localtime
  become: yes
  become_user: "{{ user.name }}"
  aur: name=localtime-git
  tags:
    - aur

- include_tasks: roles/nmtrust/tasks/unit.yaml
  vars:
    unit: localtime.service
    run_on: "{{ localtime.run_on }}"
