---
- name: Install LightDM
  pacman:
    name:
      - lightdm
#      - lightdm-gtk-greeter
      - lightdm-webkit2-greeter
      - accountsservice
#      - numlockx
    state: present

- name: Install LightDM
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name:
      - lightdm-webkit2-theme-glorious
    state: present

- name: Create autologin group
  group:
    name: autologin
    state: present

- name: Create nopasswdlogin group
  group:
    name: nopasswdlogin
    state: present

#- name: Add the user to autologin group
#  user: name={{ user.name }} groups=autologin append=yes
#  tags:
#    - user

#- name: Add the user to nopasswdlogin group
#  user: name={{ user.name }} groups=nopasswdlogin append=yes
#  tags:
#    - user

- name: Copy lightdm greeters config
  copy:
    dest: /etc/lightdm/
    src: "{{ item }}"
  with_items:
#    - lightdm-gtk-greeter.conf
    - lightdm-webkit2-greeter.conf

- name: Specify LightDM greeter session
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    regexp: "^\\#?greeter-session="
    line: "greeter-session=lightdm-webkit2-greeter"

- name: Specify LightDM greeter session wrapper
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    regexp: "^\\#?session-wrapper="
    line: "session-wrapper=/etc/lightdm/Xsession"

#- name: Specify LightDM greeter greeter setup script
#  lineinfile:
#    dest: /etc/lightdm/lightdm.conf
#    regexp: "^\\#?greeter-setup-script="
#    line: "greeter-setup-script=/usr/bin/numlockx on"
#
#- name: Specify LightDM greeter session setup script
#  lineinfile:
#    dest: /etc/lightdm/lightdm.conf
#    regexp: "^\\#?session-setup-script="
#    line: "session-setup-script=/usr/bin/numlockx on"

- name: Specify LightDM greeter autologin user
  lineinfile:
    dest: /etc/lightdm/lightdm.conf
    regexp: "^\\#?autologin-user="
    line: "autologin-user={{ user.name }}"

#- name: Specify LightDM greeter autologin session
#  lineinfile:
#    dest: /etc/lightdm/lightdm.conf
#    regexp: "^\\#?autologin-session=i3"
#    line: "autologin-session=i3"

- name: Add nopasswdlogin to lightdm pam config
  lineinfile:
    dest: /etc/pam.d/lightdm
    line: "auth        sufficient  pam_succeed_if.so user ingroup nopasswdlogin"
    insertafter: "^\\#\\%PAM"
    firstmatch: yes

- name: Enable LightDM
  systemd: name=lightdm-plymouth.service enabled=yes
  when: bootloader.plymouth == True

- name: Enable LightDM
  systemd: name=lightdm.service enabled=yes
  when: bootloader.plymouth is not defined or bootloader.plymouth == False

- name: Allow lightdm to login with PAM
  lineinfile:
    line: "+:lightdm:LOCAL"
    insertbefore: '\+:root:LOCAL'
    dest: /etc/security/access.conf
