---
- name: Install hunspell
  pacman:
    name:
      - hunspell
      - hunspell-en_US
    state: present
  tags:
    - hunspell

- name: Install hunspell-sk
  become: yes
  become_user: "{{ user.name }}"
  aur: name=hunspell-sk
  tags:
    - hunspell

- name: Install aspell
  pacman:
    name:
      - aspell
      - aspell-en
    state: present
  tags:
    - aspell

- name: Install aspell-sk
  become: yes
  become_user: "{{ user.name }}"
  aur: name=aspell-sk
  tags:
    - aspell
