---
- name: Install feh
  pacman: name=feh state=present
  tags:
    - feh

- name: Jail feh
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/feh
        state=link
  tags:
    - feh
    - firejail

- name: Install imlib2-heic
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: imlib2-heic
    skip_pgp_check: yes
  tags:
    - aur
    - feh
