---
- name: Install poppler-glib
  pacman: name=poppler-glib state=present
  tags:
    - gimp

- name: Install GIMP
  pacman:
    name:
      - gimp
      - gimp-plugin-gmic
    state: present
  tags:
    - gimp

- name: Jail GIMP
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/gimp
        state=link
  tags:
    - gimp
    - firejail

- name: Install GIMP raw support
  pacman: name=gimp-nufraw state=present
  tags:
    - gimp
