---
- include: imagemagick.yaml
- include: gimp.yaml
- include: gthumb.yaml
- include: feh.yaml
- include: qcode.yaml

- name: Install misc media codecs and helpers
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - perl-archive-zip
      - opus-tools
      - playerctl
      - a52dec
      - libmad
      - libmpeg2
      - lxappearance
      - ffmpegthumbnailer
      - vlc
    state: present

- name: Install Metadata Anonymisation Toolkit
  pacman:
    name: mat2
    state: present
  tags:
    - mat

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present

- name: Install zbar
  pacman:
    name: zbar
    state: present

- name: Install svgcleaner
  pacman:
    name: svgcleaner
    state: present

- name: Install gnome-screenshot
  pacman:
    name: gnome-screenshot
    state: present

- name: Install digikam
  pacman:
    name: digikam
    state: present

- name: Install recapp for screen recording
  aur: name=recapp-git user="{{ user.name }}"

- name: Install gtk theme
  pacman:
    name: arc-gtk-theme
    state: present

- name: Copy icon theme
  synchronize:
    dest: /usr/share/icons
    src: Green-Maia
  when: not ansible_check_mode

- name: Copy cursor theme
  synchronize:
    dest: /usr/share/icons
    src: Volantes-Cursors
  when: not ansible_check_mode

- name: Create background dir
  file: path=/usr/share/backgrounds state=directory

- name: Copy backround
  copy:
    dest: /usr/share/backgrounds/fight.jpg
    src: fight.jpg
