---
- include: beets.yaml
- include: abcde.yaml
- include: imagemagick.yaml
- include: inkscape.yaml
- include: gimp.yaml
- include: gthumb.yaml
- include: feh.yaml
- include: imv.yaml
- include: mcomix.yaml
- include: teiler.yaml
- include: flac2all.yaml
- include: darktable.yaml
- include: qcode.yaml

- name: Install misc media codecs and helpers
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - perl-archive-zip
      - opus-tools
    state: present

- name: Install Metadata Anonymisation Toolkit
  pacman:
    name: mat2
    state: present
  tags:
    - mat

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present

- name: Install zbar
  pacman:
    name: zbar
    state: present

- name: Install sxiv
  pacman:
    name: sxiv
    state: present

- name: Install svgcleaner
  pacman:
    name: svgcleaner
    state: present

- name: Install flameshot
  pacman:
    name: flameshot
    state: present

- name: Install digikam
  pacman:
    name: digikam
    state: present
