---
- include: imagemagick.yaml
- include: gimp.yaml
- include: gthumb.yaml
- include: feh.yaml
- include: qcode.yaml
- include: theme.yaml

- name: Install misc media codecs and helpers
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - perl-archive-zip
      - opus-tools
      - playerctl
      - a52dec
      - libmad
      - libmpeg2
      - lxappearance
      - ffmpegthumbnailer
      - vlc
    state: present

- name: Install Metadata Anonymisation Toolkit
  pacman:
    name: mat2
    state: present
  tags:
    - mat

- name: Install youtube-dl
  pacman:
    name: youtube-dl
    state: present

- name: Install zbar
  pacman:
    name: zbar
    state: present

- name: Install svgcleaner
  pacman:
    name: svgcleaner
    state: present

- name: Install gnome-screenshot
  pacman:
    name: gnome-screenshot
    state: present

- name: Install digikam
  pacman:
    name: digikam
    state: present

#- name: Install recapp for screen recording
#  become: yes
#  become_user: "{{ user.name }}"
#  aur:
#    name:
#      - recapp-git
#      - python-pulse-control
#    user: "{{ user.name }}"

