---
- name: Comment out root partition from fstab since we are loading it rw
  replace:
    path: /etc/fstab
    regexp: "(.*subvol=root.*)"
    replace: '#\1'
    backup: yes

- name: Add `swap to cryptsetup
  lineinfile:
    path: /etc/crypttab
    line: "swap /dev/disk/by-partlabel/cryptswap  /dev/urandom  swap,offset=2048,cipher=aes-xts-plain64,size=256"
  when: disable_swap is not defined or disable_swap != True
