---
- name: Copy crypttab.initramfs config
  copy:
    dest: /etc/crypttab.initramfs
    src: crypttab.initramfs
  notify: rebuild bootloader
  when: root_partition == "/dev/mapper/system"

- name: Comment out root partition from fstab since we are loading it rw
  replace:
    path: /etc/fstab
    regexp: "(.*subvol=root.*)"
    replace: '#\1'
    backup: yes

- name: Add swap to cryptsetup
  lineinfile:
    path: /etc/crypttab
    line: "swap /dev/disk/by-partlabel/cryptswap  /dev/urandom  swap,offset=2048,cipher=aes-xts-plain64,size=256"
  when: disable_swap is not defined or disable_swap != True

- include: microcode.yaml
- include: plymouth.yaml
  when: bootloader.plymouth is defined and bootloader.plymouth == True
- include: refind.yaml
  when: bootloader.loader == 'refind'
- include: systemd.yaml
  when: bootloader.loader == 'systemd'
