---
- name: Install bootloader
  pacman: name=refind state=present

- name: Install bootloader to boot
  command: refind-install

- name: Install plymouth
  aur:
    name: plymouth-git
    user: "{{ user.name }}"

- name: Install bootloader theme
  git:
    dest: "{{ bootloader.path }}/EFI/refind/{{ bootloader.theme_path }}"
    repo: https://github.com/bobafetthotmail/refind-theme-regular.git
    depth: 1

- name: Copy bootloader background
  copy:
    dest: "{{ bootloader.path }}/EFI/refind/{{ bootloader.theme_path }}/icons/128-48/bg_plymouth.png"
    src: plymouth/bg_plymouth.png

- name: Copy bootloader theme config
  copy:
    dest: "{{ bootloader.path }}/EFI/refind/theme.conf"
    src: theme.conf

- name: Add theme to bootloader
  lineinfile:
    path: "{{ bootloader.path }}/EFI/refind/refind.conf"
    line: "include theme.conf"

- name: Add entries to bootloader
  lineinfile:
    path: "{{ bootloader.path }}/EFI/refind/refind.conf"
    line: "include entries.conf"

- name: Copy plymouth theme
  synchronize:
    dest: /usr/share/plymouth/
    src: plymouth/themes
  notify:
    - make plymouth theme default

- name: Copy plymouth config
  copy:
    dest: /etc/plymouth/plymouthd.conf
    src: plymouth/plymouthd.conf

- name: Edit mkinitcpio config
  lineinfile:
    path: /etc/mkinitcpio.conf
    line: "HOOKS=(base systemd keyboard autodetect sd-plymouth sd-vconsole modconf block filesystems sd-encrypt btrfs)"
    regexp: "^HOOKS="
  notify:
    - rebuild bootloader

- include: microcode.yaml
- include: entries.yaml
- include: cleanup.yaml
