---

- name: Copy bootloader theme config
  template:
    dest: "{{ bootloader.path }}/EFI/refind/theme.conf"
    src: theme.conf

- name: Add our config to bootloader
  lineinfile:
    path: "{{ bootloader.path }}/EFI/refind/refind.conf"
    line: "{{ item }}"
  with_items:
    - "include theme.conf"
    - "include entries.conf"

- name: Copy crypttab.initramfs config
  copy:
    dest: /etc/crypttab.initramfs
    src: crypttab.initramfs
  notify: rebuild bootloader

- include: microcode.yaml
- include: theme.yaml
  when: bootloader.theme_path is defined and bootloader.theme_path != ''
- include: plymouth.yaml
  when: bootloader.plymouth is defined and bootloader.plymouth == True
- include: entries.yaml
- include: cleanup.yaml
