---
- name: Install refind
  pacman:
    name: refind
    state: present

- name: Install refind to boot
  shell: cmd="refind-install"

- name: Install plymouth
  aur:
    name: plymouth-git
    user: "{{ user.name }}"

- name: Install bootloader theme
  git:
    dest: "{{ bootloader.path }}/EFI/refind/{{ bootloader.theme_path }}"
    repo: "{{ bootloader.theme_repo }}"
    depth: 1

- name: Copy Arch hardened icon
  copy:
    dest: "{{ bootloader.path }}/EFI/refind/{{ bootloader.theme_path }}/icons/128-48/os_arch_hardened.png"
    src: os_arch_hardened.png

- name: Copy bootloader background
  copy:
    dest: "{{ bootloader.path }}/EFI/refind/{{ bootloader.theme_path }}/icons/128-48/bg_plymouth.png"
    src: plymouth/bg_plymouth.png

- name: Copy bootloader theme config
  template:
    dest: "{{ bootloader.path }}/EFI/refind/theme.conf"
    src: theme.conf

- name: Add theme to bootloader
  lineinfile:
    path: "{{ bootloader.path }}/EFI/refind/refind.conf"
    line: "include theme.conf"

- name: Add entries to bootloader
  lineinfile:
    path: "{{ bootloader.path }}/EFI/refind/refind.conf"
    line: "include entries.conf"

- name: Copy plymouth theme
  synchronize:
    dest: /usr/share/plymouth/
    src: plymouth/themes
  notify:
    - make plymouth theme default

- name: Copy plymouth config
  copy:
    dest: /etc/plymouth/plymouthd.conf
    src: plymouth/plymouthd.conf

- name: Copy crypttab.initramfs config
  copy:
    dest: /etc/crypttab.initramfs
    src: crypttab.initramfs
  notify: rebuild bootloader

- include: microcode.yaml
- include: entries.yaml
- include: cleanup.yaml
