---
- name: Install bootloader
  pacman: name=refind state=present

- name: Install bootloader to boot
  command: refind-install

- name: Install plymouth
  aur:
    name: plymouth-git
    user: "{{ user.name }}"

- name: Check bootloader theme folder exists
  stat:
    path: "{{ bootloader.path }}/EFI/refind/{{ bootloader.theme_path }}"
  register: bootloader_folder

- name: Install bootloader theme
  git:
    dest: "{{ bootloader.path }}/EFI/refind/{{ bootloader.theme_path }}"
    repo: "{{ bootloader.theme_repo }}"
    depth: 1
  when: bootloader.theme_repo is defined and bootloader.theme_path is defined and not bootloader_folder.stat.exists

- name: Copy Arch hardened icon
  copy:
    dest: "{{ bootloader.path }}/EFI/refind/icons/os_arch_hardened.png"
    src: os_arch_hardened.png

- name: Copy bootloader background
  copy:
    dest: "{{ bootloader.path }}/EFI/refind/{{ bootloader.theme_path }}/icons/128-48/bg_plymouth.png"
    src: plymouth/bg_plymouth.png
  when: bootloader.theme_path is defined

- name: Copy bootloader theme config
  copy:
    dest: "{{ bootloader.path }}/EFI/refind/theme.conf"
    src: theme.conf

- name: Add theme to bootloader
  lineinfile:
    path: "{{ bootloader.path }}/EFI/refind/refind.conf"
    line: "include theme.conf"

- name: Add entries to bootloader
  lineinfile:
    path: "{{ bootloader.path }}/EFI/refind/refind.conf"
    line: "include entries.conf"

- name: Copy plymouth theme
  synchronize:
    dest: /usr/share/plymouth/
    src: plymouth/themes
  notify:
    - make plymouth theme default

- name: Copy plymouth config
  copy:
    dest: /etc/plymouth/plymouthd.conf
    src: plymouth/plymouthd.conf

- include: microcode.yaml
- include: entries.yaml
- include: cleanup.yaml
