---
- name: Install plymouth
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: plymouth-git

- name: Copy plymouth theme
  synchronize:
    dest: /usr/share/plymouth/
    src: plymouth/themes
  notify:
    - make plymouth theme default

- name: Copy plymouth config
  copy:
    dest: /etc/plymouth/plymouthd.conf
    src: plymouth/plymouthd.conf
