---
- name: Install zip archive utilities
  pacman:
    name:
      - zip
      - unzip
      - p7zip
    state: present
  tags:
    - zip

- name: Install unrar
  pacman: name=unrar state=present
  tags:
    - unrar

- name: Install atool
  pacman: name=atool state=present
  tags:
    - atool

- name: Install hashdeep
  pacman: name=hashdeep state=present
  tags:
    - hashdeep

- name: Install par2cmdline
  pacman: name=par2cmdline state=present
  tags:
    - par2

- name: Install ddrescue
  pacman: name=ddrescue state=present
  tags:
    - ddrescue

- name: Install lesspipe
  pacman: name=lesspipe state=present
  tags:
    - lesspipe

- name: Install geteltorito
  aur: name=geteltorito user={{ user.name }}
  tags:
    - aur
    - geteltorito
