---
- name: start macchiato
  systemd: name=macchiato.service state=started
  when: network.spoof_mac == True and running_in_chroot == False

- name: stop macchiato
  systemd: name=macchiato.service state=stopped
  when: network.spoof_mac == False and running_in_chroot == False
