---
- name: Install docker
  pacman:
    name:
      - docker
      - docker-compose
    state: present

- name: Add user to docker group
  user: name={{ user.name }} groups=docker append=yes
  tags:
    - user

- name: Create docker config dir
  file:
    path: /etc/docker
    state: directory

- name: Copy docker daemon settings
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: Enable docker.service
  systemd:
    name: docker.service
    enabled: yes
