---
- name: install greenclip from AUR
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: gnome-shell-extension-clipboard-indicator
  tags:
    - aur
  when: desktop_environment == 'gnome'

- include: greenclip.yaml
  when: desktop_environment != 'gnome'
