hostname:

video_drivers:
  - nvidia

pacman_packages:
  - w3m

bootloader:
  path: /boot
  time: -1
  theme_path: ~
  theme_repo: ~
  kernel_parameters:
  silent: False
  plymouth: False

additional_hosts: |
  192.168.2.110 control-plane

aur_packages:
  - yay
  - ctop
  - downgrade
  - libnvidia-container-bin
  - libnvidia-container-tools-bin
  - nvidia-container-toolkit

ssh:
  port: 22
  user_dir: /install/.ssh
  enable_sshd: True

kubernetes:
  roles:
    - control-plane
    - node
