hostname: aluhome

video_drivers:
  - nvidia

#hardened:
#  enable_namespaces: true

display_manager: lightdm
desktop_environment: xfce-i3

firewall:
    xdebug: true
    avahi: true

bootloader:
  loader: systemd
  path: /boot
  time: 3
  kernel_parameters:
  silent: False
  plymouth: False

pacman_additional_packages:
  - networkmanager-l2tp
  - strongswan
