hostname: aluhome

video_drivers:
  - nvidia

#hardened:
#  enable_namespaces: true

display_manager: lightdm

firewall:
    xdebug: true
    avahi: true

bootloader:
  loader: systemd
  path: /boot
  time: 3
  kernel_parameters:
  silent: False
  plymouth: False

pacman_additional_packages:
  - networkmanager-l2tp
  - strongswan
  - kubectl

aur_additional_packages:
  - gotask-taskfile-bin
  - rke-bin
