hostname: aluhtpc

video_drivers:
  - nvidia

pacman_packages:

additional_hosts:

aur_packages:
  - yay
  - ctop
  - downgrade
  - nvidia-container-toolkit

ssh:
  port: 22
  user_dir: /install/.ssh
  enable_sshd: True
