hostname: alu-worker-1

video_drivers:
  - nvidia

pacman_packages:
  - w3m

additional_hosts: |
  192.168.2.100 control-plane

aur_packages:
  - yay
  - ctop
  - downgrade
  - libnvidia-container-bin
  - libnvidia-container-tools-bin
  - nvidia-container-toolkit

ssh:
  port: 22
  user_dir: /install/.ssh
  enable_sshd: True

kubernetes:
  roles:
    - control-plane
    - node
