---
- name: Install GNUradio
  pacman:
    name: gnuradio
    state: present

- name: Install hamlib
  pacman:
    name: hamlib
    state: present

- include: rtl-sdr.yaml
- include: radio_mgmt.yaml
- include: radio_ops.yaml
