---
- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Add archlinux gpg keys
  command:
    cmd: pacman-key -u --populate archlinux

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install inetutils for hostname
  pacman:
    name: inetutils
    state: present

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- name: Add localhost to hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 localhost localhost.localdomain'

- name: Add ipv6 localhost to hosts
  lineinfile:
    path: /etc/hosts
    line: '::1 localhost localhost.localdomain'

- name: Add host to hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.1.1 {{ hostname }} {{ hostname }}.localdomain'
  when: hostname is defined

- name: Add additional hosts
  blockinfile:
    path: /etc/hosts
    block: "{{ additional_hosts }}"
  when: additional_hosts is defined

- name: set inotify limit higher
  lineinfile:
    path: /etc/sysctl.d/90-inotify.conf
    line: "fs.inotify.max_user_watches=524288"
    create: yes
  notify:
    - reload sysctl

- include: locale.yaml
- include: shell.yaml
- include: user.yaml
- include: sudo.yaml
- include: packages.yaml
- include: journal.yaml
- include: xdg.yaml
- include: gnome-keyring.yaml
