---
- name: Copy pacman configuration file
  copy:
    src: pacman/pacman.conf
    dest: /etc/pacman.conf

- name: Make sure pacman hooks dir exists
  file: path=/etc/pacman.d/hooks state=directory mode="0755"

- name: Copy pacman hooks
  copy:
    src: "pacman/{{ item }}.hook"
    dest: "/etc/pacman.d/hooks/{{ item }}.hook"
  with_items:
    - arch-audit
    - orphans

- name: Add archlinux gpg keys
  command:
    cmd: pacman-key -u --populate archlinux

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes

- name: Install inetutils for hostname
  pacman:
    name: inetutils
    state: present

- name: Set the hostname
  lineinfile:
    path: /etc/hostname
    line: "{{ hostname }}"
    create: yes
  when: hostname is defined and hostname != ''

- name: Set the hostname
  lineinfile:
    path: /etc/hostname
    line: "{{ inventory_hostname }}"
    create: yes
  when: hostname is not defined or hostname == ''

- name: Add localhost to hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 localhost localhost.localdomain'

- name: Add ipv6 localhost to hosts
  lineinfile:
    path: /etc/hosts
    line: '::1 localhost localhost.localdomain'

- name: Add host to hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.1.1 {{ hostname }} {{ hostname }}.localdomain'
  when: hostname is defined

- name: Add additional hosts
  blockinfile:
    path: /etc/hosts
    block: "{{ additional_hosts }}"
  when: additional_hosts is defined

- name: set inotify limit higher
  lineinfile:
    path: /etc/sysctl.d/90-inotify.conf
    line: "fs.inotify.max_user_watches=524288"
    create: yes
  notify:
    - reload sysctl

- name: Restricting access to kernel logs
  lineinfile:
    path: /etc/sysctl.d/51-dmesg-restrict.conf
    line: "kernel.dmesg_restrict = 1"
    create: yes
  notify:
    - reload sysctl

- name: enable sysrq
  lineinfile:
    path: /etc/sysctl.d/99-sysrq.conf
    line: "kernel.sysrq=1"
    create: yes
  notify:
    - reload sysctl

- name: Restrict user login with PAM
  blockinfile:
    block: |
      +:{{ user.name }}:LOCAL
      +:root:LOCAL
      +:(wheel):LOCAL
      -:ALL:ALL
    path: /etc/security/access.conf

- name: Limit amount of processes
  blockinfile:
    block: |
      * soft nproc 2500
      * hard nproc 3000
    path: /etc/security/limits.conf

- include: locale.yaml
- include: shell.yaml
- include: user.yaml
- include: sudo.yaml
- include: packages.yaml
- include: journal.yaml
- include: xdg.yaml
