---
- name: Install universal base packages
  pacman:
    name: "{{ pacman_base_packages }}"
    state: present
  tags:
    - packages

- name: Install non-essential packages
  pacman:
    name: "{{ pacman_packages }}"
    state: present
  tags:
    - packages
    - additional

- name: Install additional packages
  pacman:
    name: "{{ pacman_additional_packages }}"
    state: present
  tags:
    - packages
    - additional
  when: pacman_additional_packages is defined and (pacman_additional_packages|length>0)

- name: Create pacman hook directory
  file: path=/etc/pacman.d/hooks state=directory
  tags:
    - packages

- name: Use all cores when compressing packages
  lineinfile:
    dest: /etc/makepkg.conf
    regexp: "^COMPRESSXZ"
    line: "COMPRESSXZ=(xz -c -z - --threads=0)"

- name: Install AUR base packages
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name: "{{ aur_packages }}"
  tags:
    - aur
    - packages

- name: Install AUR additional packages
  pacman:
    name: "{{ aur_additional_packages }}"
    state: present
  tags:
    - aur
    - packages
    - additional
  when: aur_additional_packages is defined and (aur_additional_packages|length>0)

- name: Push pacman cache cleanup service
  copy: src=paccache.service dest=/etc/systemd/system/paccache.service
  notify:
    - reload systemd config
  tags:
    - packages

- name: Push pacman cache cleanup timer
  copy: src=paccache.timer dest=/etc/systemd/system/paccache.timer
  notify:
    - reload systemd config
    - restart paccache
  tags:
    - packages

- name: Enable and start pacman cache cleanup timer
  systemd: name=paccache.timer enabled=yes
  notify: start paccache
  tags:
    - packages
