---
- name: Install xdg-user-dirs
  pacman: name=xdg-user-dirs state=present
  tags:
    - xdg

- name: Create user directories
  command: /usr/bin/xdg-user-dirs-update
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - xdg

- name: Verify autostart dir exists
  file: path=/home/{{ user.name }}/.config/autostart state=directory
  tags:
    - xdg

- name: Install perl-file-mimeinfo
  pacman: name=perl-file-mimeinfo state=present
  tags:
    - xdg
