---
- name: Install XFCE and i3 packages
  pacman:
    name:
#      - dunst
      - python-pywal
      - python-dbus
      - picom
      - i3-gaps
      - exo
      - garcon
      - libxfce4ui
      - libxfce4util
      - thunar
      - thunar-volman
      - thunar-media-tags-plugin
      - thunar-archive-plugin
      - tumbler
      - xfce4-dev-tools
      - xfce4-power-manager
      - xfce4-session
      - xfce4-settings
      - xfconf
      - xcb-util-cursor
      - awesome
      - light-locker
    state: present

- name: Install XFCE and i3 aur packages
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name:
      - i3-volume
      - autotiling
      - rofi-git
      - polybar
      - python-fontawesome
      - i3gopher
      - i3icons2-git
      - xfce4-i3-workspaces-plugin
  tags:
    - aur

- name: Copy the autostart scripts
  copy:
    src: /usr/share/applications/{{item}}
    dest: /home/{{ user.name }}/.config/autostart/
    owner: {{ user.name }}
    group: {{ user.group }}
  with_items:
    - picom.desktop
    - nm-applet.desktop
#    - protonmail-bridge.desktop
#    - spotify.desktop
#    - thunderbird.desktop
    - i3.desktop

- name: Remove previous xfce4 sessions
  file:
    path: /home/{{ user.name }}/.cache/sessions
    state: absent

- name: Create xfce4 configuration directory in user home
  file:
    path: /home/{{ user.name }}/.config/xfce4/xfconf/xfce-perchannel-xml
    owner: {{ user.name }}
    group: {{ user.group }}
    state: directory

- name: Copy xfce4 configuration file
  copy:
    src: xfce/{{item}}
    dest: /home/{{ user.name }}/.config/xfce4/xfconf/xfce-perchannel-xml/{{item}}
    owner: {{ user.name }}
    group: {{ user.group }}
  with_items:
    - xfce4-keyboard-shortcuts.xml
    - xfce4-session.xml
    - keyboards.xml
    - xfce4-power-manager.xml
    - xsettings.xml
    - xfce4-notifyd.xml
