---
- name: restart cups
  systemd: name=cups.service state=restarted
  when: ansible_is_chroot == False

- name: start cups
  systemd: name=cups.service state=started
  when: ansible_is_chroot == False
