---
- name: Install syncthing
  pacman: name=syncthing state=present

- include_tasks: roles/nmtrust/tasks/unit.yaml
  vars:
    unit: syncthing.service
    run_on: "{{ syncthing.run_on }}"
    user_unit: true
