---
- name: Install magic-wormhole
  become: yes
  become_user: "{{ user.name }}"
  aur:
    name:
      - python-hkdf
      - python-spake2
      - python-txtorcon
      - magic-wormhole
  tags:
    - aur

- name: Jail magic-wormhole
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/wormhole
        state=link
  tags:
    - firejail
  when: firejail.enabled is defined and firejail.enabled == True

- name: Push magic-wormhole firejail profile
  copy: src=firejail/wormhole.profile dest=/usr/local/etc/firejail/wormhole.profile
  notify:
    - activate firejail profiles
  tags:
    - firejail
  when: firejail.enabled is defined and firejail.enabled == True
